- name: Ra lệnh Deploy
      run: |
        gcloud run deploy recsys-app \
          --project recsys-ai \
          --region asia-southeast1 \
          --source . \
          --allow-unauthenticated \
          --quiet \
          --no-cache